add interface for creating and closing listeners
tarantool/httpng pull request #107
Opened 2021-04-29 16:44 UTC by artemreyt

Added a single interfaces to register and close, start read, stop read,
listener sockets.
It helps to manipulate by listener sockets better in single place.
Also, added closing sockets in some places where it should be.

2021-04-30 07:38 UTC, void234 commented on httpng/httpng.c
> +	if (listener_idx > conf.num_listeners)
>=

2021-04-30 07:39 UTC, void234 commented on httpng/httpng.c
> +	for (unsigned listener_idx = 0; listener_idx < conf.num_listeners;
This wouldn't compile with older compilers.

unsigned listener_idx;
for(...

2021-04-30 07:40 UTC, void234 commented on httpng/httpng.c
> +static void close_listener_cfgs_sockets()
static void close_listener_cfgs_sockets(void)

There are below.

2021-04-30 07:41 UTC, void234 commented on httpng/httpng.c
> +#error open_worker_socket() not implemented for libuv yet
Quotes

2021-04-30 07:50 UTC, void234 commented on httpng/httpng.c
> +	if (listener_ctx->sock == NULL)
It is never NULL

2021-04-30 07:55 UTC, void234 commented on httpng/httpng.c
> +static bool open_worker_socket(thread_ctx_t *thread_ctx, unsigned listener_idx)
prepare_listening_socket() seems to be more appropriate name

2021-04-30 07:56 UTC, void234 commented on httpng/httpng.c
> +	} else {
"{" is not needed here according to Tarantool coding style

2021-04-30 07:57 UTC, void234 commented on httpng/httpng.c
>  	listener_ctx_t *listener_ctx = &thread_ctx->listener_ctxs[0];
This line and several more below can be moved into open_worker_socket() thus making init_worker_thread() shorter and easier to read.

2021-04-30 07:58 UTC, void234 commented on httpng/httpng.c
> +	if (!listener_cfg->is_opened)
assert() ?

2021-04-30 07:59 UTC, void234 commented on httpng/httpng.c
> +	for (unsigned listener_idx = 0;
Older compilers

2021-04-30 08:03 UTC, void234 commented on httpng/httpng.c
> +		listener_idx < thread_ctx->listeners_created; ++listener_idx) {
4 spaces, not full tab - the distinction between condition/increment and branches should be clearly visible.

2021-04-30 08:05 UTC, void234 commented on httpng/httpng.c
> +		++listener_idx)
4 spaces

2021-04-30 08:07 UTC, void234 commented on httpng/httpng.c
> +static void worker_sockets_stop_read(thread_ctx_t *thread_ctx)
listening sockets
There and below

2021-04-30 09:06 UTC, void234 commented on httpng/httpng.c
> +	if (!open_worker_socket(thread_ctx, 0))
Maybe it would be better to prepare_listening_sockets() - all at once?

2021-04-30 09:08 UTC, void234 commented on httpng/httpng.c
> +	bool is_opened;
It is actually misleading - only "primary" fd is tracked. Are you sure this approach works well with initialization error handling?

2021-04-30 09:11 UTC, void234 commented on httpng/httpng.c
> +		conf.num_listeners * sizeof(*conf.listener_cfgs));
calloc()?

2021-04-30 09:13 UTC, void234 commented on httpng/httpng.c
> +			if (fd == -1 || !register_listener_cfgs_socket(fd, 0)) {
"< 0" while we are at it

2021-04-30 09:18 UTC, void234 commented on httpng/httpng.c
> +			int fd = open_listener_ipv4("0.0.0.0", port);
const
Just to keep the same style.
(It also helps with bugs and makes compiler optimizer work easier).

2021-04-30 09:19 UTC, void234 requested changes
Please see comments above

2021-05-12 09:57 UTC, artemreyt commented on httpng/httpng.c
> +	bool is_opened;
Yes, it tracks only "primary" fds at `conf.listener_cfgs`.
Functions 
```C
static void close_listener_cfgs_sockets();
static void close_worker_sockets(thread_ctx_t *thread_ctx);
```
are setted in way not to interfere with each other.
The second one will close primary fds if `thread_ctx->idx == 0`.

P.S.: renamed `close_worker_sockets()` -> `close_listening_sockets()`.

2021-05-12 09:57 UTC, artemreyt commented on httpng/httpng.c
> +	if (listener_idx > conf.num_listeners)
Changed to `assert()`.
Added `const`s for function arguments.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +static void close_listener_cfgs_sockets()
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +	for (unsigned listener_idx = 0; listener_idx < conf.num_listeners;
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +#error open_worker_socket() not implemented for libuv yet
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +	if (!listener_cfg->is_opened)
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +	} else {
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +	if (listener_ctx->sock == NULL)
Yes, I thought `h2o_evloop_socket_create()` can return NULL in case of error, but it seems that will be `abort()` .


> It is never NULL

Removed, done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +	for (unsigned listener_idx = 0;
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +static void worker_sockets_stop_read(thread_ctx_t *thread_ctx)
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +		listener_idx < thread_ctx->listeners_created; ++listener_idx) {
Done. And above also.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +		++listener_idx)
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +		++listener_idx)
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
>  	listener_ctx_t *listener_ctx = &thread_ctx->listener_ctxs[0];
See `prepare_listening_sockets()`.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +		conf.num_listeners * sizeof(*conf.listener_cfgs));
Done.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +			int fd = open_listener_ipv4("0.0.0.0", port);
Done + added `const` in some places where variable shouldn't change a value.

2021-05-12 09:58 UTC, artemreyt commented on httpng/httpng.c
> +			if (fd == -1 || !register_listener_cfgs_socket(fd, 0)) {
Done.

2021-05-12 09:59 UTC, artemreyt commented on httpng/httpng.c
> +	if (!open_worker_socket(thread_ctx, 0))
Agree, done.
All `listener_ctxs` now are filled in ` prepare_listening_sockets()`.

2021-05-12 18:51 UTC, void234 commented on httpng/httpng.c
> +	if (listener_idx > conf.num_listeners)
I usually do not use const for function arguments - just because it does not play well with 80 columns. And you have exceeded this limit.

2021-05-12 19:14 UTC, void234 commented on httpng/httpng.c
> +	listener_cfg_t *listener_cfg = &conf.listener_cfgs[listener_idx];
Please use "const" for new code - the whole httpng uses this approach and it is better for code style to be consistent.

2021-05-12 19:15 UTC, void234 commented on httpng/httpng.c
> +		listener_ctx_t *listener_ctx = &thread_ctx->listener_ctxs[listener_idx];
Please format for 80 columns.

2021-05-12 19:26 UTC, void234 commented on httpng/httpng.c
> +			if (fd < 0 || !register_listener_cfgs_socket(fd, 0)) {
"void register_listener_cfgs_socket(...)"
This way you would never leak fd :-)

2021-05-12 19:27 UTC, void234 requested changes
Please fix minor issues mentioned above

2021-05-13 11:56 UTC, artemreyt commented on httpng/httpng.c
> +static bool register_listener_cfgs_socket(const int fd, const unsigned listener_idx)
Done.

2021-05-13 11:56 UTC, artemreyt commented on httpng/httpng.c
> +	listener_cfg_t *listener_cfg = &conf.listener_cfgs[listener_idx];
Did you mean "don't use"?

2021-05-13 11:56 UTC, artemreyt commented on httpng/httpng.c
> +		listener_ctx_t *listener_ctx = &thread_ctx->listener_ctxs[listener_idx];
Done.

2021-05-13 11:56 UTC, artemreyt commented on httpng/httpng.c
> +			if (fd < 0 || !register_listener_cfgs_socket(fd, 0)) {
Done.

2021-05-13 12:11 UTC, void234 commented on httpng/httpng.c
> +	listener_cfg_t *listener_cfg = &conf.listener_cfgs[listener_idx];
"listener_cfg_t *const listener_cfg = ..."
Feel free to use const for function parameters - but please keep within 80 columns.

2021-05-13 12:35 UTC, void234 requested changes

2021-05-13 12:35 UTC, void234 commented on httpng/httpng.c
>  /* TODO: add Libuv support */
Please combine these comments into one (multiline). If you really need this "TODO" (I believe "#error" is enough).
There and elsewhere.

2021-05-13 12:35 UTC, void234 commented on httpng/httpng.c
> +/* Launched in  HTTP server thread */
Spaces, dot.

2021-05-13 12:35 UTC, void234 commented on httpng/httpng.c
> +/* Can be launched in TX thread or HTTP server thread. */
This is VERY useful comment - that is why I asked for them.
We can't safely call h2o_socket_close() from TX thread (thread-local variables, access to structs w/o mutexes...). Please investigate and fix this.

2021-05-13 12:50 UTC, void234 commented on httpng/httpng.c
> +		listener_ctx->sock = h2o_evloop_socket_create(thread_ctx->loop,
We can't call h2o_evloop_socket_create() from TX thread. You would see crashes on shutdown/hot reload.

2021-05-13 17:32 UTC, artemreyt commented on httpng/httpng.c
>  /* TODO: add Libuv support */
Done.

2021-05-13 17:32 UTC, artemreyt commented on httpng/httpng.c
> +/* Launched in  HTTP server thread */
Done.

2021-05-13 17:32 UTC, artemreyt commented on httpng/httpng.c
> +/* Can be launched in TX thread or HTTP server thread. */
Added argument `bool in_tx_thread`.

2021-05-13 17:32 UTC, artemreyt commented on httpng/httpng.c
> +		listener_ctx->sock = h2o_evloop_socket_create(thread_ctx->loop,
Removed.

2021-05-14 10:21 UTC, void234 commented on httpng/httpng.c
> +	listener_cfg_t * const listener_cfg =
I suggest ```*const``` (w/o space), like everywhere else in this file. This is the most readable variant in my opinion.

2021-05-14 10:23 UTC, void234 commented on httpng/httpng.c
> +static void register_listener_cfgs_socket(int fd, unsigned listener_idx)
Please put type on a separate line for new functions. I would fix everything else in httpng.c later to avoid merge/rebase issues. Somehow I forgot about that point in the Tarantool C style guide.

2021-05-14 10:26 UTC, void234 commented on httpng/httpng.c
> +			&conf.listener_cfgs[listener_idx];
One tab or half tab, but definitely not two. Not sure what the coding style guide says.

2021-05-14 10:27 UTC, void234 commented on httpng/httpng.c
> +			if ((listener_ctx->fd = dup(listener_cfg->fd)) == -1)
```< 0```

2021-05-14 10:28 UTC, void234 commented on httpng/httpng.c
> +				    bool in_tx_thread)
Too many tabs.

2021-05-14 10:31 UTC, void234 submitted a review, later dismissed
Please fix cosmetics and squash for the final look.

2021-05-14 15:56 UTC, artemreyt commented on httpng/httpng.c
> +	listener_cfg_t * const listener_cfg =
Done.

2021-05-14 15:56 UTC, artemreyt commented on httpng/httpng.c
> +static void register_listener_cfgs_socket(int fd, unsigned listener_idx)
Done.

2021-05-14 15:56 UTC, artemreyt commented on httpng/httpng.c
> +			&conf.listener_cfgs[listener_idx];
Done.

2021-05-14 15:56 UTC, artemreyt commented on httpng/httpng.c
> +			if ((listener_ctx->fd = dup(listener_cfg->fd)) == -1)
Done.

2021-05-14 15:56 UTC, artemreyt commented on httpng/httpng.c
> +				    bool in_tx_thread)
Removed the second argument.

2021-05-14 15:56 UTC, artemreyt commented
@void234, I would request you for else one review on these PR, because I changed logic a little.

2021-05-14 16:09 UTC, void234 commented on httpng/httpng.c
> +#endif /* USE_LIBUV */
`#else`

2021-05-14 16:30 UTC, artemreyt commented on httpng/httpng.c
> +#endif /* USE_LIBUV */
Done.

2021-05-14 16:37 UTC, artemreyt commented
@void234, commits were squashed, ready for final look and merge.

2021-05-14 17:59 UTC, void234 requested changes
Please look at all places where `listener_cfgs[0]` or `listener_ctxs[0]` are used and fix them - either use loops or helper functions. You can just add `#error` for libuv. We do not want compilable but incorrect-for-multilisten code, that is why I have asked for this pull request.
Other parts of code for libuv are already uncompilable, but you can add `#error` there also I you want to.

2021-05-14 18:49 UTC, artemreyt commented
> Please look at all places where `listener_cfgs[0]` or `listener_ctxs[0]` are used and fix them - either use loops or helper functions.

It is already done for non-libuv code.

> You can just add `#error` for libuv. We do not want compilable but incorrect-for-multilisten code, that is why I have asked for this pull request.

Done in separate commit.

> And rebase before doing that, please.

Done.

2021-05-14 19:55 UTC, void234 commented
> > Please look at all places where `listener_cfgs[0]` or `listener_ctxs[0]` are used and fix them - either use loops or helper functions.
> 
> It is already done for non-libuv code.

Incorrect, you have committed fixed code only after my comment.

2021-05-14 20:00 UTC, void234 approved these changes

2021-05-14 20:00 UTC, merged