doc: add listen api
tarantool/httpng pull request #158
Opened 2021-06-05 18:24 UTC by artemreyt

Added api for `listen` table to `doc/api.md`.

2021-06-07 08:21 UTC, void234 commented on doc/api.md
> +- `listen`: Table or integer or string, depending on a case. We have such term as listener-conf that is an entity describing one listener (IP:port pair).
1) Fields are listed in alphabetical order.
2) Description is too large to fit into this list (unreadable), please move it into separate sections like it is done for handlers.
3) Please use Grammarly (free version is enough) or whatever tool use prefer to fix grammar errors.

2021-06-07 08:23 UTC, void234 commented on doc/api.md
> +    - `addr`: String. IPv4/IPv6 address or hostname. If is empty then 2 listeners with '0.0.0.0' and '::' addresses are created.
You haven't implemented hostname support (yet?), I just checked. You should fix either code or documentation.

Personally, I do not think there should be support for hostnames here. What do you plan to do if hostname has been changed when the server is already launched? How often would you check?..

2021-06-07 08:25 UTC, void234 commented on doc/api.md
> +    - `tls`: Array of tables. Each table contains fields `certificate_file` and `certificate_key_file` which are strings with paths of certificate file and private key for a certificate accordingly.
Both are "files".
You should also emphasize "insecure HTTP".

2021-06-07 08:26 UTC, void234 commented on doc/api.md
> +    - `uses_sni`: Boolean. Describes to enable TLS SNI or not. `false`, by default.
"Specifies whether to enable..."

2021-06-07 08:29 UTC, void234 commented on doc/api.md
> +            { certificate_file = 'foo.com_cert.pem', certificate_key_file = 'foo.com_key.pem' },
I suggest using absolute pathnames in examples. You can use calculated ones if you like - but not relative. Too fragile and insecure.

2021-06-07 08:32 UTC, void234 commented on doc/api.md
> +  There's also an opportunity to listen on the same port but on different IP-addresses and on the same IP-address but on different ports.
Do you have some special syntax for that? If not, why mention this at all and confuse users?

2021-06-16 08:44 UTC, artemreyt commented on doc/api.md
> +- `listen`: Table or integer or string, depending on a case. We have such term as listener-conf that is an entity describing one listener (IP:port pair).
> 1. Fields are listed in alphabetical order.

Done.

> 2. Description is too large to fit into this list (unreadable), please move it into separate sections like it is done for handlers.

Moved in a separate section.

> 3. Please use Grammarly (free version is enough) or whatever tool use prefer to fix grammar errors.

Thanks, used.

2021-06-16 08:44 UTC, artemreyt commented on doc/api.md
> +    - `addr`: String. IPv4/IPv6 address or hostname. If is empty then 2 listeners with '0.0.0.0' and '::' addresses are created.
Removed from doc.

2021-06-16 08:45 UTC, artemreyt commented on doc/api.md
> +    - `tls`: Array of tables. Each table contains fields `certificate_file` and `certificate_key_file` which are strings with paths of certificate file and private key for a certificate accordingly.
Done.

2021-06-16 08:45 UTC, artemreyt commented on doc/api.md
> +    - `uses_sni`: Boolean. Describes to enable TLS SNI or not. `false`, by default.
Done.

2021-06-16 08:45 UTC, artemreyt commented on doc/api.md
> +            { certificate_file = 'foo.com_cert.pem', certificate_key_file = 'foo.com_key.pem' },
Done.

2021-06-16 08:45 UTC, artemreyt commented on doc/api.md
> +  + Integer. Defines port to listen by http.
> "..by HTTP(S) server"

No, if listener-conf is an integer only http protocol can be used.
Changed to "Defines port. In this case will be created listeners with mentioned port on default IP addresses to listen by insecure HTTP protocol."

2021-06-16 08:45 UTC, artemreyt commented on doc/api.md
> +  There's also an opportunity to listen on the same port but on different IP-addresses and on the same IP-address but on different ports.
No, removed from doc.

2021-06-16 11:23 UTC, void234 commented on doc/api.md
> +        -- Any requests to [::] (https://[::]:3300)
Not clear enough. You should add a comment that a user's browser would refuse to accept such a page unless `foo.com` in DNS or /etc/hosts points to the HTTPS server's IP.

2021-06-16 11:31 UTC, void234 commented on doc/api.md
> +        listen = 'http://foo.com'
It listens on port 80 (as was requested by @Mons), not on 3300.

2021-06-16 11:39 UTC, void234 commented on doc/api.md
> +- `listen`: Table or integer or string, depending on a case. We have such term as listener-conf that is an entity describing one listener (IP:port pair).
> > 1. Description is too large to fit into this list (unreadable), please move it into separate sections like it is done for handlers.
> 
> Moved in a separate section.

You still should note the existence of this field with "...for more details please see a section below".
 
> > 1. Please use Grammarly (free version is enough) or whatever tool use prefer to fix grammar errors.
> 
> Thanks, used.

BTW, you can use https://markdown-it.github.io/ with Grammarly if you like.

2021-06-16 11:40 UTC, void234 requested changes
Please see comments above.

2021-06-17 09:53 UTC, artemreyt commented on doc/api.md
> +        -- Any requests to [::] (https://[::]:3300)
> a user's browser would refuse to accept such a page unless `foo.com` in DNS or /etc/hosts points to the HTTPS server's IP.

I think it's obvious. It's basic of client-server architecture, isn't it?

2021-06-17 10:25 UTC, void234 commented on doc/api.md
> +        -- Any requests to [::] (https://[::]:3300)
> > a user's browser would refuse to accept such a page unless `foo.com` in DNS or /etc/hosts points to the HTTPS server's IP.
> 
> I think it's obvious. It's the basics of client-server architecture, isn't it? The client should know IP-address of the server. The domain mentioned in the certificate doesn't matter in this case.

It does. If DNS says "foo.tarantool.io 188.93.56.54" but the certificate says "bar.tarantool.io" - a user browser would refuse to show the web page, that's the idea.

2021-06-18 09:26 UTC, artemreyt commented on doc/api.md
> +        listen = 'http://foo.com'
Changed to 80 port.

2021-06-18 09:26 UTC, artemreyt commented on doc/api.md
> +        -- Any requests to [::] (https://[::]:3300)
> a user's browser would refuse to accept such a page unless foo.com in DNS or /etc/hosts points to the HTTPS server's IP.

Ok. Added this note.

2021-06-18 13:53 UTC, void234 commented on doc/api.md
> +    - `addr`: String. IPv4/IPv6 address. If it is empty then 2 listeners with '0.0.0.0' and '::' addresses are created.
`addr = ''` causes "Can't parse IP address" so this description is not accurate.

2021-06-18 13:59 UTC, void234 commented on doc/api.md
> +        -- Note: a user's browser would refuse to accept such a page unless foo.com in DNS or /etc/hosts points to the HTTPS server's IP.
"Note: a user's browser would refuse to accept such a page unless it attempts to access the website from this certificate (`foo.com` in this example)".

2021-06-18 14:04 UTC, void234 commented on doc/api.md
> +  + String. Describes URI. Note: HTTPS protocol can't be enabled in this way because `tls` can be defined only if listener-conf is a table.
`listen = { 'https://foo.tarantool.io' }` enables insecure HTTP on port 443. This is quite a bad idea. I believe you should fix the code (throw error) in a separate PR.

2021-06-18 14:05 UTC, void234 requested changes
Please see the comments above. We are nearly there.

2021-06-18 14:28 UTC, artemreyt commented on doc/api.md
> +    - `addr`: String. IPv4/IPv6 address. If it is empty then 2 listeners with '0.0.0.0' and '::' addresses are created.
Changed `empty` to `nil`.

2021-06-18 14:28 UTC, artemreyt commented on doc/api.md
> +        -- Note: a user's browser would refuse to accept such a page unless foo.com in DNS or /etc/hosts points to the HTTPS server's IP.
Done.

2021-06-18 14:28 UTC, artemreyt commented on doc/api.md
> +  + String. Describes URI. Note: HTTPS protocol can't be enabled in this way because `tls` can be defined only if listener-conf is a table.
Will be done in a separate PR

2021-06-18 14:38 UTC, merged