early implement multilisten
tarantool/httpng pull request #72
Opened 2021-04-16 19:55 UTC by artemreyt

Added functionality to configure listeners via httpng.cfg{listen}.
Now is able:
  * IPv4 and IPv6;
  * listen on any port with the same IP addresses;
  * listen on IP address with any ports;
  * http/https;
  * set any SSL certificates on one listener (SNI) - no wildcard and SAN;

Ways to configure listen:
```
  * listen = { <number> } -- listen on default IP addresses with port=<number> by http;
  * listen = 'http' -- listen on default IP addresses on 80 port by http;
  * listen = 'http://<ip-addr>:<port>' -- listen on <ip-addr>:<port> by http;
  * listen = {
      {
        addr = <string>,
        port = <number>,
        tls = nil or {
          { certificate_file = <cert_file>, certificate_key_file = <key_file> },
          { certificate_file = <cert_file>, certificate_key_file = <key_file> },
          ...
        }
        uses_sni = <bool> -- false by default, should be enabled explicitly
      }
    }
```
There's opportunity to mix ways in one 'listen', just list them separated by commas
in the table 'listen'.

Not ready for production usage. Now doesn't support Libuv.

Tests are added now without `sh` script due to not final implementation.
Now you can test by hand: `tarantool tests/listen_test.lua <test_case_name>`, e.g.:
* `tarantool tests/listen_test.lua 2_listeners_with_tls`
* `sudo tarantool tests/listen_test.lua only_port_80`
* etc.

2021-04-20 16:48 UTC, Totktonada commented on httpng.lua
> +local function get_clear_listen_confs_from_string(listen_conf)
Do you look into the built-in `uri.parse(<...>)`?

2021-04-20 16:49 UTC, Totktonada commented on httpng.lua
> +#!/usr/bin/env tarantool
Is it expected to be run as a script?

2021-04-20 16:50 UTC, artemreyt commented on httpng.lua
> +local function get_clear_listen_confs_from_string(listen_conf)
> Do you look into the built-in `uri.parse(<...>)`?

Yes, it is used in this function.

2021-04-20 16:52 UTC, artemreyt commented on httpng.lua
> +#!/usr/bin/env tarantool
No, needed to remove.

2021-04-21 11:29 UTC, void234 commented on CMakeLists.txt
> +set(HEADERS httpng/openssl_utils.h)
Why remove include/tarantool-httpng/httpng.h? This way we wouldn't forget how it should be named ;-)

2021-04-21 11:30 UTC, void234 commented on examples/basic_get.lua
> +
Why?

2021-04-21 11:30 UTC, void234 commented on examples/benchmark_hello.lua
> +local TESTDIR = fio.dirname(fio.abspath(arg[0]))
Why CAPS?

2021-04-21 11:33 UTC, void234 commented on httpng/httpng.c
> +		SSL_CTX     *ssl_ctx;
Extra spaces

2021-04-21 11:34 UTC, void234 commented on httpng/httpng.c
> +	long     min_tls_proto_version;
Extra spaces

2021-04-21 11:35 UTC, artemreyt commented on CMakeLists.txt
> +set(HEADERS httpng/openssl_utils.h)
Why do we need another directory for includes? Our headers are only needed inside httpng sources.

2021-04-21 11:38 UTC, artemreyt commented on httpng/httpng.c
> +	long     min_tls_proto_version;
Just wanted to align fields...but, sure, whole source should have one style.

2021-04-21 11:38 UTC, void234 commented on httpng/httpng.c
>  	if (uv_tcp_init(thread_ctx->ctx.loop, &listener_ctx->uv_tcp_listener))
This code should be properly indented.

2021-04-21 11:41 UTC, void234 commented on httpng/httpng.c
> +				goto dup_failed;
You have code after goto; you are not freeing allocated resources. And please do not forget about fd_consumed (you can revamp code however you like).

2021-04-21 11:45 UTC, void234 commented on httpng/httpng.c
> +int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr);
Declarations should go into the beginning of file whenever possible. Declarations for not-static functions must go into .h which must be also included by compilation unit where such function is defined (fool-proofing).

We should probably increase warning level for httpng (can't easily do this for h2o) so it would complain about that.

2021-04-21 11:56 UTC, void234 commented on httpng/httpng.c
>  		fprintf(stderr, "Using default min_proto_version=tls1.2\n");
What would happen if cfg() is called with some low min_proto_version, then shutdown(), then cfg() called w/o min_proto_version? I suspect it would use "old" insecure min_proto_version (which is bad) and print "Using default min_proto_version=tls1.2" (which is even worse).

You should rework applying default settings, especially ones concerning security.

2021-04-21 12:00 UTC, void234 commented on httpng/httpng.c
> +	long openssl_security_level = my_lua_tointegerx(L, -1, &is_integer);
Why have you replaced "uint64_t" with "long"? Now it accepts e. g. "-1" (see check below) which is incorrect.
Why you are using local var "openssl_security_level" instead of "conf.openssl_security_level"?

2021-04-21 14:37 UTC, void234 commented on CMakeLists.txt
> +set(HEADERS httpng/openssl_utils.h)
Sure, private headers should be in httpng/. Just do not touch "include/tarantool-httpng/httpng.h" which does not exist in master branch at the moment. We do have plans for some kind of public C API in roadmap.

2021-04-21 14:38 UTC, void234 commented on httpng/httpng.c
> +	long     min_tls_proto_version;
Speaking about style - please do not use C++-style single line comments in httpng.c

2021-04-22 06:38 UTC, void234 commented on httpng.lua
> +			protocol = 'tcp'})
Indentation

2021-04-22 06:41 UTC, void234 commented on httpng.lua
> +	for i, v in ipairs(arr) do
Global variables

2021-04-22 06:46 UTC, void234 commented on httpng.lua
> +	return type(obj) == "number" and math.floor(obj) == obj and true or false
Why "and true or false"?

2021-04-22 06:47 UTC, void234 commented on httpng.lua
> +local default_listen_port = 3300
Why have you changed default from 8080?

2021-04-22 06:48 UTC, void234 commented on httpng.lua
> +-- If IP adress isn't defined, create listeners with the same other parameters
address

2021-04-22 06:49 UTC, void234 commented on httpng.lua
> +	for protocol, defaults in pairs(protocol_defaults) do
Global variables

2021-04-22 06:50 UTC, void234 commented on httpng.lua
> +-- If listen is a table and array(contains only [1...#listen-1] indexes),
Why "-1"?

2021-04-22 06:52 UTC, void234 commented on httpng.lua
> +local function get_clear_listen_conf(listen_conf)
"clean" there and elsewhere.

2021-04-22 06:54 UTC, void234 commented on httpng.lua
> +		assert(#listen_conf.tls > 1 and listen_conf.uses_sni or #listen_conf.tls == 1)
Please add braces for clarity.

2021-04-22 06:57 UTC, void234 commented on httpng.lua
> +		error(("incorrect port value (must be in interval (0, %s]):\n")
The check is for 0 inclusive, error message is for 0 exclusive. Please make up your mind.

2021-04-22 07:02 UTC, void234 commented on httpng.lua
> +		error("'uses_sni' can't be false or nil if there're certificates more than 1:\n" .. print_table_to_string(listen_conf))
"...if there is more than one certificate".
BTW, do we really need configuration option "uses_sni"? Why not simply count table entries and decide?

2021-04-22 07:03 UTC, void234 commented on httpng.lua
> +	for _, tls_config in ipairs(tls) do
Global variables

2021-04-22 07:03 UTC, void234 commented on httpng.lua
> +	for _, addr in ipairs(default_ip_addresses) do
Global variables

2021-04-22 07:06 UTC, void234 commented on httpng.lua
> +			error("unknown protocol recieved: " .. protocol)
There is a typo in "received". But "specified" is more appropriate here anyway.

2021-04-22 07:09 UTC, void234 commented on httpng.lua
> +			else
There is no need for "else" after goto. Indentation is better. I suggest invert condition and get rid of "else".

2021-04-22 07:15 UTC, void234 commented on httpng.lua
> +				log.error("impossible to parse URI: " .. listen_conf)
If this is error, why there is no goto/return? Shouldn't this be a warning?

2021-04-22 07:16 UTC, void234 commented on httpng.lua
> +			log.error("unknown hostame: " .. host)
If this is error, why there is no goto/return? Shouldn't this be a warning?

2021-04-22 07:18 UTC, void234 commented on httpng.lua
> +	for addr_port, duplicate_listeners in pairs(duplicate_listen) do
Global variables

2021-04-22 07:21 UTC, void234 commented on httpng.lua
> +	local function tprint(tbl, indent, str_res)
"4 spaces instead tabs"
https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/

2021-04-22 07:23 UTC, void234 commented on httpng/multilisten.c
> +static int ip_version(const char *src) {
"However, there is one special case, namely functions: they have the opening brace at the beginning of the next line"
https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/
There and elsewhere.

2021-04-22 07:27 UTC, void234 commented on httpng/multilisten.c
> +	char buf[16];
"char buf[sizeof(struct in6_addr)]" or "struct in6_addr buf". There is no need to hardcode size, this is error-prone and unreadable.

2021-04-22 07:27 UTC, void234 commented on httpng/multilisten.c
> +	} else if (inet_pton(AF_INET6, src, buf)) {
You do not really need "else" here

2021-04-22 07:29 UTC, void234 commented on httpng/multilisten.c
> +	snprintf(port_str, STR_PORT_LENGTH, "%d", port);
"sizeof(port_str)" is more readable and foolproof

2021-04-22 07:31 UTC, void234 commented on httpng/multilisten.c
> +	int fd;
Why "fd" is defined here?

2021-04-22 07:36 UTC, void234 commented on httpng/multilisten.c
> +		sizeof(reuseaddr_flag)) != 0) {
Multi-line "if"s should use "half-tab" (4 spaces) indentation for second and following condition lines for readability - to distinguish condition logic from action logic (or whatever it is named).
There and elsewhere.

2021-04-22 07:37 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "setting cloexec failed";
FD_CLOEXEC

2021-04-22 07:37 UTC, void234 commented on httpng/multilisten.c
> +		perror("bind error");
perror()?

2021-04-22 07:39 UTC, void234 commented on httpng/multilisten.c
> +			*lerr = "setting TCP_DEFER_ACCEPT failed";
Actually this is just performance optimization, you can print warning and continue

2021-04-22 07:42 UTC, void234 commented on httpng/multilisten.c
> +#else
#else/#endif comments everywhere. It tends to grow and complicate to complete unreadability.

2021-04-22 07:45 UTC, void234 commented on httpng/multilisten.c
> +		goto close_fd;
You should name your "error" labels for "what failed", not "what to do". This way you should not change them when more logic is added.

2021-04-22 07:46 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "sni_ctxs_capacity <= ssl_cts_size";
typo

2021-04-22 07:53 UTC, void234 commented on httpng/multilisten.c
> +	if (sni_map->ssl_ctxs_capacity <= sni_map->ssl_ctxs_size) {
"..size >= ...capacity" is more readable.
There and elsewhere.

2021-04-22 07:56 UTC, void234 commented on httpng/multilisten.c
> +	sni_map->ssl_ctxs_capacity = 0;
If you want to initialize to zero field of zeroized memory - that's fine (this is not hot path), but you are not doing that consistently, see sni_fields_capacity. I believe it is better to remove extra lines of code.

2021-04-22 07:56 UTC, void234 commented on httpng/multilisten.c
> +	const char * common_name = get_subject_common_name(X509_cert);
spaces

2021-04-22 07:58 UTC, void234 commented on httpng/multilisten.c
> +static int sni_map_insert(sni_map_t *sni_map, const char *certificate_file, const char *certificate_key_file, const char **lerr) {
80 columns.
There and elsewhere.

2021-04-22 08:01 UTC, void234 commented on httpng/multilisten.c
> +#define GET_REQUIRED_LISTENER_FIELD(name, lua_ttype, convert_func_postfix) \
do {...} while(0)

2021-04-22 08:02 UTC, void234 commented on httpng/multilisten.c
> +	lua_pop(L, 1); \
Why "\"?

2021-04-22 08:06 UTC, void234 commented on httpng/multilisten.c
> +	assert(certs_num == 1);
Maybe you should change this assert() and the one below to returning error? assert()'s wouldn't work in release build.

2021-04-22 08:07 UTC, void234 commented on httpng/multilisten.c
> +	sni_map_t *sni_map = (servername_callback_arg_t *) arg;
spaces

2021-04-22 08:07 UTC, void234 commented on httpng/multilisten.c
> +		fprintf(stderr, "Server name is not recieved:%s\n", servername);
"specified"

2021-04-22 08:19 UTC, void234 commented on httpng/multilisten.c
> +			goto sni_map_insert_fail;
Don't you need lua_pop() here (not sure)?

2021-04-22 08:21 UTC, void234 commented on httpng/multilisten.c
> +	if (uses_sni)
Tertiary operator would make code shorter and more readable

2021-04-22 08:22 UTC, void234 commented on httpng/multilisten.c
> +int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr) {
Why CAPS?

2021-04-22 08:24 UTC, void234 commented on httpng/multilisten.c
> +		goto listen_invalid_type;
You can invert condition and get rid of "else"

2021-04-22 08:27 UTC, void234 commented on httpng/multilisten.c
> +		lua_pop(L, 1); /* pop tls */
Why don't you pop 2 below?

2021-04-22 08:28 UTC, void234 commented on httpng/multilisten.c
> +	++need_to_pop;
int need_to_pop = 1;

2021-04-22 08:30 UTC, void234 commented on httpng/openssl_utils.c
> +		return NULL;
Hmm

2021-04-22 08:30 UTC, void234 commented on httpng/openssl_utils.c
> +	if (!cert) {
== NULL

2021-04-22 08:31 UTC, void234 commented on httpng/openssl_utils.c
> +	if (!fp) {
== NULL

2021-04-22 08:32 UTC, void234 commented on httpng/openssl_utils.c
> +	if (cert == NULL) {
Why?

2021-04-22 08:32 UTC, artemreyt commented on httpng.lua
> +local default_listen_port = 3300
It's Mons API.

2021-04-22 08:33 UTC, void234 commented on httpng/openssl_utils.c
> +		free((char *)common_name);
Why cast?

2021-04-22 08:36 UTC, artemreyt commented on httpng.lua
> +		error("'uses_sni' can't be false or nil if there're certificates more than 1:\n" .. print_table_to_string(listen_conf))
Because user may want to receive a request only if there is host secured by given certificate. In this case SNI will work.

2021-04-22 08:37 UTC, void234 commented on httpng/openssl_utils.c
> +						int level, long min_proto_version, const char **lerr) {
Indentation overkill (and we need 80 columns max)

2021-04-22 08:39 UTC, void234 commented on httpng/openssl_utils.c
> +			fprintf(stderr, "certificate file: %s\n", certificate_file);
If you want debug output - please make it a macro and disable it in release (or, even better, enable it only in your working copy)

2021-04-22 08:40 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "setting cloexec failed";
What is wrong?

2021-04-22 08:42 UTC, void234 commented on httpng/openssl_utils.c
> +#ifdef DISABLE_HTTP2
DISABLE_HTTP2 is defined in httpng.c so this won't work, please be more careful with #ifdefs.
In this case it is better to move defining DISABLE_HTTP2 from httpng.c to CMakeLists.txt

2021-04-22 08:43 UTC, void234 commented on httpng/openssl_utils.c
> +
Extra line

2021-04-22 08:44 UTC, void234 requested changes
Please see comments above

2021-04-22 08:44 UTC, artemreyt commented on httpng/multilisten.c
> +	assert(certs_num == 1);
Expected that this can't happen if code is written right. So works only in debug.

2021-04-22 08:50 UTC, void234 commented on httpng.lua
> +local default_listen_port = 3300
Can you please provide quote/URL for "3300"?

2021-04-22 08:55 UTC, void234 commented on httpng.lua
> +		error("'uses_sni' can't be false or nil if there're certificates more than 1:\n" .. print_table_to_string(listen_conf))
And what is the point of that? Wrong certificate wouldn't be accepted by client anyway (would error even be different?). Why make things more complicated?

2021-04-22 09:00 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "setting cloexec failed";
Other error messages use exact names for constants, this one - not.

2021-04-22 09:04 UTC, void234 commented on httpng/multilisten.c
> +	assert(certs_num == 1);
You are using unfiltered user input. asserts are for programmer errors.

2021-04-22 09:08 UTC, artemreyt commented on httpng.lua
> +		error("'uses_sni' can't be false or nil if there're certificates more than 1:\n" .. print_table_to_string(listen_conf))
> And what is the point of that? Wrong certificate wouldn't be accepted by client anyway (would error even be different?).

That will be on client side it's not our deal (maybe he wants to crash our server or so on). He can turn off checking certificates, but our wish may be don't receive a request to host that not specified in certificate, right?

>Why make things more complicated?

It's advanced option, by default it is transparently understandable.

2021-05-19 16:37 UTC, artemreyt commented on httpng.lua
> +	for i, v in ipairs(arr) do
Where are global variables?

2021-05-19 16:53 UTC, artemreyt commented on httpng.lua
> +	for addr_port, duplicate_listeners in pairs(duplicate_listen) do
Where?

2021-05-19 16:54 UTC, artemreyt commented on httpng.lua
> +	for _, addr in ipairs(default_ip_addresses) do
Where? `addr` is local.

2021-05-19 18:20 UTC, artemreyt commented on httpng/httpng.c
> +int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr);
Made as static function, because `multilisten_get_listen_from_lua()` depends on global `conf`.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +
Done

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +#ifdef DISABLE_HTTP2
Replaced to CMakeLists.txt.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +			fprintf(stderr, "certificate file: %s\n", certificate_file);
Removed.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +						int level, long min_proto_version, const char **lerr) {
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +		free((char *)common_name);
Remove cast.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +	if (!cert) {
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +	if (!fp) {
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/openssl_utils.c
> +		return NULL;
Removed.

2021-05-20 13:14 UTC, artemreyt commented on httpng/multilisten.c
> +		lua_pop(L, 1); /* pop tls */
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/multilisten.c
> +int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr) {
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/multilisten.c
> +	if (uses_sni)
Done.

2021-05-20 13:14 UTC, artemreyt commented on httpng/multilisten.c
> +	sni_map_t *sni_map = (servername_callback_arg_t *) arg;
Done.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +#define GET_REQUIRED_LISTENER_FIELD(name, lua_ttype, convert_func_postfix) \
Done.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "sni_ctxs_capacity <= ssl_cts_size";
Done.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +static int sni_map_insert(sni_map_t *sni_map, const char *certificate_file, const char *certificate_key_file, const char **lerr) {
Done in whole file.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +	sni_map->ssl_ctxs_capacity = 0;
Removed.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +		sizeof(reuseaddr_flag)) != 0) {
Done everywhere.

2021-05-20 13:15 UTC, artemreyt commented on httpng/multilisten.c
> +	char buf[16];
Done.

2021-05-20 13:38 UTC, artemreyt commented
Fixed all Sergey comments.
Adapted new socket interface to this branch.
Plus changed some code-style things as return values of functions on the separate line.

2021-05-20 13:41 UTC, artemreyt commented on httpng/multilisten.c
> +			goto sni_map_insert_fail;
Done.

2021-05-20 13:41 UTC, void234 commented on httpng.lua
> +	for i, v in ipairs(arr) do
There is no `local i, v` so `i` and `v` are global. Am I wrong?

2021-05-20 13:42 UTC, void234 commented on httpng.lua
> +	for addr_port, duplicate_listeners in pairs(duplicate_listen) do
`addr_port`, `duplicate_listeners`

2021-05-20 13:44 UTC, void234 commented on httpng.lua
> +	for _, addr in ipairs(default_ip_addresses) do
> Where? `addr` is local.

Why do you think that it is local?

2021-05-20 13:51 UTC, artemreyt commented on httpng.lua
> +	for _, addr in ipairs(default_ip_addresses) do
> > Where? `addr` is local.
> 
> Why do you think that it is local?

If to analyze this example, I think they are local.
```Lua
-- for_i.lua:
g_j = 1
print(g_j, _G["g_j"])

for i in ipairs({1, 2}) do
    print(i, _G["i"])
end
```
```
$ tarantool for_i.lua
1       1
1       nil
2       nil
```

2021-05-20 13:59 UTC, void234 commented on httpng/multilisten.c
> +	assert(certs_num == 1);
> > You are using unfiltered user input. asserts are for programmer errors.
> 
> That's not right, it is filtered in Lua.

This makes your code too fragile.
This is not a hot path so I believe it worths some `if`s unless it makes code too complicated - and I do not believe that it does.

2021-05-20 14:07 UTC, void234 commented on httpng/multilisten.c
> +static int sni_map_insert(sni_map_t *sni_map, const char *certificate_file, const char *certificate_key_file, const char **lerr) {
You have missed a couple of places (but please do not touch existing code, I would fix it separately).

2021-05-20 14:15 UTC, void234 commented on httpng.lua
> +	for i, v in ipairs(arr) do
Yes, I am wrong. Sorry.

2021-05-20 14:36 UTC, void234 commented on CMakeLists.txt
> +set(HEADERS httpng/openssl_utils.h)
set(HEADERS ${HEADERS} httpng/openssl_utils.h)

2021-05-20 14:39 UTC, void234 commented on examples/basic_get.lua
> +local foo_key_path = fio.pathjoin(testdir, '../tests/foo.tarantool.io_key.pem')
`dofile()` instead of copy-paste into many files?

2021-05-20 14:41 UTC, void234 commented on httpng/httpng.c
>  #define USE_HTTPS 1
Do you still need that?

2021-05-20 14:48 UTC, void234 commented on httpng/multilisten.c
> +	sni_map->sni_fields = calloc(certs_num, sizeof(*sni_map->ssl_ctxs));
Wrong sizeof()!

2021-05-20 15:12 UTC, void234 commented on httpng/httpng.c
> -	close_listener_cfgs_sockets();
You are not closing sockets in case of an initialization error.

2021-05-20 15:13 UTC, void234 commented on httpng/multilisten.c
> +	if (ai_family == -1) {
`< 0`

2021-05-20 15:13 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "Can't detect IP address";
"parse"

2021-05-20 15:14 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "create socket(2) failed";
"(2)"?

2021-05-20 21:53 UTC, artemreyt commented on CMakeLists.txt
> +set(HEADERS httpng/openssl_utils.h)
Done.

2021-05-20 21:55 UTC, artemreyt commented on examples/basic_get.lua
> +local foo_key_path = fio.pathjoin(testdir, '../tests/foo.tarantool.io_key.pem')
Done.
(Realized via `_G` table as `dofile()` requires global vars, but `luacheck` doesn't swear at `_G`)

2021-05-20 21:55 UTC, artemreyt commented on httpng/httpng.c
>  #define USE_HTTPS 1
No, removed.

2021-05-20 21:56 UTC, artemreyt commented on httpng/httpng.c
> +				&conf.listener_cfgs[listener_idx];
Effects after rebase. Done.

2021-05-20 21:56 UTC, artemreyt commented on httpng/httpng.c
> -	close_listener_cfgs_sockets();
Yes.
Also there was wrong label order: `invalid_openssl_security_level` and `min_proto_version_invalid` should be before `listen_invalid`, fixed it.
Added `close_listener_cfgs_sockets()` before `listen_invalid`.

2021-05-20 21:56 UTC, artemreyt commented on httpng/multilisten.c
> +	if (ai_family == -1) {
Done.

2021-05-20 21:56 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "Can't detect IP address";
Done.

2021-05-20 21:56 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "create socket(2) failed";
> "(2)"?

`man 2 socket`. But it is not needed here, so removed.

2021-05-20 21:56 UTC, artemreyt commented on httpng/multilisten.c
> +	sni_map->sni_fields = calloc(certs_num, sizeof(*sni_map->ssl_ctxs));
Fixed.

2021-05-20 21:56 UTC, artemreyt commented on httpng/multilisten.c
> +	assert(certs_num == 1);
Done.

2021-05-21 07:59 UTC, void234 commented on httpng/httpng.c
> +static int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr);
Not only CAPS - it matches the name of a constant.

2021-05-21 08:04 UTC, void234 commented on httpng/httpng.c
> +			listener_cfg_t * const listener_cfg =
Why have you added extra space here?

Please do not touch whitespaces in existing code even when they violate the coding style. If you really want to - do that in a separate commit. This way it is more readable and easier to rebase/merge.

2021-05-21 08:41 UTC, void234 commented on httpng/openssl_utils.c
> +	assert(cert_path != NULL);
Why you are checking `cert_path` but not `lerr`? Inconsistent.

2021-05-21 08:44 UTC, void234 commented on httpng/openssl_utils.c
> +		assert(*lerr != NULL);
`assert(cert != NULL || *lerr != NULL)`

2021-05-21 08:44 UTC, artemreyt commented on httpng/openssl_utils.c
> +	assert(cert_path != NULL);
Why should I check lerr? I can override it anyway.

2021-05-21 08:45 UTC, artemreyt commented on httpng/openssl_utils.c
> +	assert(cert_path != NULL);
Oh, sorry, you meant checking char **

2021-05-21 08:52 UTC, void234 commented on httpng/openssl_utils.c
> +	char *common_name = calloc(length + 1, sizeof(*common_name));
I believe it is better to check for NULL here. It works now but the code is fragile. This is not a hot path.

2021-05-21 09:05 UTC, void234 commented on httpng/multilisten.c
> +	X509 *X509_cert = get_X509_from_certificate_path(certificate_file, lerr);
You have forgotten `X509_free()` when there is no error - here if you do not need `*X509_cert` anymore, somewhere around on_shutdown otherwise.

2021-05-21 09:11 UTC, void234 commented on httpng/multilisten.c
> +conf_sni_map_cleanup()
`(void)`

2021-05-21 09:17 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "certs num must be 1 when not using sni";
"only one key/certificate pair can be specified if SNI is disabled"

2021-05-21 09:18 UTC, void234 commented on httpng/multilisten.c
> +#ifndef NDEBUG
???

2021-05-21 09:19 UTC, void234 commented on httpng/multilisten.c
> +	assert(lua_istable(L, -1));
`if`

2021-05-21 09:26 UTC, void234 commented on httpng/multilisten.c
> +	for (size_t i = 0; i < sni_map->sni_fields_size; ++i) {
Older compilers - please move the definition of `i` out.

2021-05-21 09:29 UTC, void234 commented on httpng/multilisten.c
> +		if (strcasecmp(servername,
Why case insensitive? This is a hot path, domain names are lower case...
I suggest a comparison of length and `memcmp()`.

2021-05-21 09:33 UTC, void234 commented on httpng/multilisten.c
> +			if (SSL_set_SSL_CTX(s, ssl_ctx) != ssl_ctx) {
You should just check for NULL, it can't return some other context.

2021-05-21 09:36 UTC, void234 commented on httpng/multilisten.c
> +		conf.min_tls_proto_version ,lerr);
Whitespaces

2021-05-21 09:37 UTC, void234 commented on httpng/multilisten.c
> +		(servername_callback_arg_t *) sni_map);
Whitespaces

2021-05-21 09:37 UTC, void234 commented on httpng/multilisten.c
> +		       bool uses_sni, const char **lerr)
Whitespaces

2021-05-21 09:38 UTC, void234 commented on httpng/multilisten.c
> +	assert(lua_istable(L, -1));
`if`s instead of asserts

2021-05-21 10:07 UTC, void234 commented on httpng/multilisten.c
> +			*lerr = "clear <listen-conf> isn't a table";
Sysadmins have no idea what is "clear <listen-conf>".
Please choose a little more readable error message.

2021-05-21 10:09 UTC, void234 commented on httpng/multilisten.c
> +			goto clear_listen_conf_fail;
`failed_parsing_clean_listen_conf`?

2021-05-21 10:09 UTC, void234 commented on httpng/multilisten.c
> +		uint16_t    port;
Whitespaces

2021-05-21 10:10 UTC, void234 commented on httpng/multilisten.c
> +			if (ssl_ctx == NULL) {
No {}

2021-05-21 10:14 UTC, void234 commented on examples/basic_get.lua
> +        },
`dofile()` instead of copy-paste into multiple files?

2021-05-21 10:20 UTC, artemreyt commented on examples/basic_get.lua
> +        },
dofile() only loads certificate/key pairs. Now, there're 2 pairs, and somewhere 1 pair necessary needed, in another place both. Write 3 files for dofile()? (1st for load, 2nd for pasting one pair, 3rd for pasting both)

2021-05-21 10:23 UTC, void234 commented on httpng.lua
> +::return_get_clean_lc_from_str:: return res
Label on a separate line, please.

2021-05-21 10:37 UTC, void234 commented on httpng.lua
> +}
Unextensible.

```
function table.copy(t)
    local u = {}
    for k, v in pairs(t) do u[k] = v end
    return setmetatable(u, getmetatable(t))
end

local result = table.copy(httpng_c)
result.cfg = cfg
return result
```

2021-05-21 11:03 UTC, void234 commented on examples/basic_get.lua
> +        },
dofile(dofile())?
Just use your common sense. Too much copy-paste is bad, too much complexity is also bad. Good balance is called engineering.

2021-05-21 18:22 UTC, artemreyt commented on httpng/multilisten.c
> +		       bool uses_sni, const char **lerr)
On GitHub tab is 6 spaces. In 8-spaces tab it is aligned by first argument.

2021-05-24 20:39 UTC, artemreyt commented on httpng/multilisten.c
> +		if (strcasecmp(servername,
Done. Move type of `sni_map->hostname` to `h2o_iovec`.

2021-05-24 20:44 UTC, artemreyt commented on examples/basic_get.lua
> +local foo_key_path = fio.pathjoin(testdir, '../tests/foo.tarantool.io_key.pem')
Done.

2021-05-24 20:44 UTC, artemreyt commented on httpng.lua
> +::return_get_clean_lc_from_str:: return res
Done.

2021-05-24 20:44 UTC, artemreyt commented on httpng.lua
> +}
Agree, done.

2021-05-24 20:44 UTC, artemreyt commented on httpng/httpng.c
> +static int multilisten_get_listen_from_lua(lua_State *L, int LUA_STACK_IDX_TABLE, const char **lerr);
Done.

2021-05-24 20:44 UTC, artemreyt commented on httpng/multilisten.c
> +	X509 *X509_cert = get_X509_from_certificate_path(certificate_file, lerr);
Done. Added.

2021-05-24 20:44 UTC, artemreyt commented on httpng/multilisten.c
> +	for (size_t i = 0; i < sni_map->sni_fields_size; ++i) {
Done.

2021-05-24 20:44 UTC, artemreyt commented on httpng/multilisten.c
> +			if (ssl_ctx == NULL) {
Done.

2021-05-25 09:03 UTC, void234 commented on httpng/httpng.c
> +static int multilisten_get_listen_from_lua(lua_State *L, int lua_stack_idx_table, const char **lerr);
80 columns

2021-05-25 09:05 UTC, void234 commented on httpng/httpng.c
> +	;
`;` is not needed here.

2021-05-25 09:08 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "can't parse certificate file";
`get_X509_from_certificate_path()` have filled in `*lerr`, why are you overwriting it?

2021-05-25 09:21 UTC, void234 commented on httpng/multilisten.c
> +		*lerr = "certificates number and `uses_sni` contradict "
Please make this message easier to understand by inexperienced sysadmins.

2021-05-25 09:23 UTC, void234 commented on httpng/multilisten.c
> +			*lerr = "listeners are bad parsed";
Personally, I can't parse this error message.

2021-05-25 09:27 UTC, void234 requested changes
Please see the comments above.
Please fix existing tests - there are definitely some regressions.

2021-05-25 11:01 UTC, artemreyt commented on httpng/httpng.c
> +static int multilisten_get_listen_from_lua(lua_State *L, int lua_stack_idx_table, const char **lerr);
Done.

2021-05-25 11:02 UTC, artemreyt commented on httpng/httpng.c
> +	;
Removed.

2021-05-25 11:02 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "can't parse certificate file";
Removed overwriting.

2021-05-25 11:02 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "certificates number and `uses_sni` contradict "
Redone -> "`uses_sni` is false, but more than one certificate provided".

2021-05-25 11:02 UTC, artemreyt commented on httpng/multilisten.c
> +			*lerr = "listeners are bad parsed";
Redone -> `listen` must be table of tables.

2021-05-25 12:57 UTC, artemreyt commented
> Please see the comments above.
> Please fix existing tests - there are definitely some regressions.

Done.
There were fails due to a lua wrapper `httpng.cfg()` of C `cfg()` returned error when called with `pcall()` with prefix pointed to a place where C `cfg()`were called .

2021-05-25 13:14 UTC, void234 commented
> > Please see the comments above.
> > Please fix existing tests - there are definitely some regressions.
> 
> Done.
> There were fails due to a lua wrapper `httpng.cfg()` of C `cfg()` returned error when called with `pcall()` with prefix pointed to a place where C `cfg()`were called .

A lot of tests still fail.
There are still a lot of "unresolved" issues, please comment or mark them as resolved if the code has already been fixed.

2021-05-25 13:16 UTC, artemreyt commented on examples/basic_get.lua
> +        },
Made one file `ssl_pairs.lua` which loads ssl pairs.

2021-05-25 13:20 UTC, artemreyt commented on httpng/multilisten.c
> +		*lerr = "certs num must be 1 when not using sni";
Done.

2021-05-25 13:20 UTC, artemreyt commented on httpng/openssl_utils.c
> +	char *common_name = calloc(length + 1, sizeof(*common_name));
Done.

2021-05-25 15:07 UTC, artemreyt commented
> A lot of tests still fail.

Done. All tests are passed on Ubuntu.

> There are still a lot of "unresolved" issues, please comment or mark them as resolved if the code has already been fixed.
Done. Commented the remaining ones.

2021-05-26 08:39 UTC, void234 commented
> > There are still a lot of "unresolved" issues, please comment or mark them as resolved if the code has already been fixed.
> 
> Done. Commented the remaining ones.

No, you didn't - A LOT of "conversations" are still unresolved and uncommented. You can simply "resolve" them if the code has already been fixed.

2021-05-26 08:54 UTC, artemreyt commented on httpng.lua
> +				log.error("impossible to parse URI: " .. listen_conf)
Changed to `error()`

2021-05-26 08:54 UTC, artemreyt commented on httpng.lua
> +			log.error("unknown hostame: " .. host)
Changed to `error()`

2021-05-26 11:29 UTC, void234 commented
I believe it is time to integrate multilisten.c into httpng.c (please try to avoid declarations, it is usually possible to move new functions into appropriate place). Fold commits and do some self-review before final look.
openssl_utils.* is fine as it is (when you would format it for 80 columns).

You should probably keep this branch for the moment (just rename it).

2021-05-26 14:42 UTC, artemreyt commented
> I believe it is time to integrate multilisten.c into httpng.c (please try to avoid declarations, it is usually possible to move new functions into appropriate place). Fold commits and do some self-review before final look.
> openssl_utils.* is fine as it is (when you would format it for 80 columns).

Done.

> You should probably keep this branch for the moment (just rename it).

Made branch `artemreyt/multilisten_copy_before_integrate`.

2021-05-27 09:00 UTC, void234 commented
Please format commit message for 80 columns.

2021-05-27 09:02 UTC, void234 commented on examples/long_response.lua
> -
Please do not touch unrelated whitespaces.

2021-05-27 09:05 UTC, void234 commented on httpng.lua
> +function table.copy(t)
local?

2021-05-27 09:06 UTC, void234 commented on httpng.lua
> +        protocol = 'tcp'})
Keep "{" "}" on the same line maybe?

2021-05-27 09:08 UTC, void234 commented on httpng.lua
> +            table.insert(res, get_clean_listen_conf({addr = ip_addrs[i], port = port}))
80 columns.

2021-05-27 09:11 UTC, void234 commented on httpng.lua
> +            error("impossible to parse URI: " .. listen_conf)
goto? Indentation?

2021-05-27 09:13 UTC, void234 commented on httpng.lua
> +            if not port then
`not port` here, `port == nil` below. Is this intentional?

2021-05-27 09:20 UTC, void234 commented on httpng/httpng.c
> +	SSL_CTX *ssl_ctx;
You can make it the first member to avoid holes in this struct.

2021-05-27 09:22 UTC, void234 commented on httpng/httpng.c
> +	sni_map_t **sni_maps;
Please keep pointers together to avoid holes in this struct. I usually order fields "largest first".

2021-05-27 09:24 UTC, void234 commented on httpng/httpng.c
> +	long min_tls_proto_version;
Likewise, please move these fields to `double`s.

2021-05-27 09:25 UTC, void234 commented on httpng/httpng.c
> +typedef sni_map_t servername_callback_arg_t;
Please move this up, I try to keep `typedef`s before variable definitions.

2021-05-27 09:27 UTC, void234 commented on httpng/httpng.c
> +/* Returns file descriptor or -1 on error */
Sentences should end with a dot according to the Tarantool code style guide.

2021-05-27 09:27 UTC, void234 commented on httpng/httpng.c
> +	if ((fd = socket(res->ai_family, flags, 0)) == -1) {
`< 0`

2021-05-27 09:37 UTC, void234 commented on httpng/httpng.c
> +	if (sni_map->sni_fields_size >= sni_map->sni_fields_capacity) {
`assert()`s? Is it possible for the end users to cause such errors?

2021-05-27 09:42 UTC, void234 commented on httpng/httpng.c
> +		goto tls_pair_not_a_table;
Are you sure `get_ssl_ctx_not_uses_sni()` does enough `lua_pop()` calls in case of errors?

2021-05-27 09:43 UTC, void234 commented on httpng/httpng.c
> +/* FIXME: report to log */
Indentation.

2021-05-27 09:45 UTC, void234 commented on httpng/httpng.c
> +		*lerr = "only one key/certificate pair can be"
You can and should ignore indentation rules to avoid splitting string literals.
Or can use `#define`s or `const`s with short names.
There and everywhere in new code.

2021-05-27 09:58 UTC, void234 commented on httpng/httpng.c
> +multilisten_get_listen_from_lua(lua_State *L, int lua_stack_idx_table,
Please choose a more readable name for this function, those which better describes what it does.

2021-05-27 10:01 UTC, void234 commented on httpng/openssl_utils.h
> +
```
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
```

2021-05-27 10:09 UTC, void234 commented on tests/listen_test.lua
> +#!/usr/bin/env tarantool
tests folder contains automatic tests, this one is not. Move it to examples? Automate using luatest? We would need automatic tests anyway, but I believe we should merge first.
Please format it for 80 columns and clean up debug comments.

2021-05-27 10:10 UTC, void234 requested changes
Please see comments above.

2021-05-27 19:01 UTC, artemreyt commented on httpng.lua
> +function table.copy(t)
It's impossible to add 'local' for field of global `table`.
Also, I found that in Tarantool there is extended `table`. See [table module documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/table/).
And there's already `copy()` method exists, which copies an array.
But there's also such method that we need called `table.deepcopy()`.

2021-05-27 19:14 UTC, artemreyt commented on httpng.lua
> +            error("impossible to parse URI: " .. listen_conf)
Yes, this error is thrown if the last condition is false.

2021-05-27 19:19 UTC, artemreyt commented on httpng.lua
> +        protocol = 'tcp'})
Done.

2021-05-27 19:19 UTC, artemreyt commented on httpng.lua
> +            table.insert(res, get_clean_listen_conf({addr = ip_addrs[i], port = port}))
Done.

2021-05-27 19:19 UTC, artemreyt commented on httpng.lua
> +            if not port then
Yes, wrote `port == nil` in both places.

2021-05-28 08:04 UTC, artemreyt commented on httpng/httpng.c
> +	SSL_CTX *ssl_ctx;
Done.

2021-05-28 08:04 UTC, artemreyt commented on httpng/httpng.c
> +	sni_map_t **sni_maps;
Done.

2021-05-28 08:04 UTC, artemreyt commented on httpng/httpng.c
> +	long min_tls_proto_version;
Done.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +typedef sni_map_t servername_callback_arg_t;
So, this `typedef` is before variable definition.
Just `sni_map_t` is used as argument for `SSL_CTX_set_tlsext_servername_arg()` function, that is far below.
But I've moved this `typedef` right after `sni_map_t` definition.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +/* Returns file descriptor or -1 on error */
Done. And everywhere in code.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +	if ((fd = socket(res->ai_family, flags, 0)) == -1) {
Done.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +		goto tls_pair_not_a_table;
Ah, yes, it doesn't.
Added `lua_pop()` to if block.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +/* FIXME: report to log */
Done.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +		*lerr = "only one key/certificate pair can be"
Done here and everywhere in new code.

2021-05-28 08:05 UTC, artemreyt commented on httpng/httpng.c
> +multilisten_get_listen_from_lua(lua_State *L, int lua_stack_idx_table,
`load_and_handle_listen_from_lua()` describes fully, in my opinion.

2021-05-28 08:09 UTC, artemreyt commented on httpng/openssl_utils.h
> +
Done.

2021-05-28 08:11 UTC, artemreyt commented on examples/long_response.lua
> -
Done.

2021-05-28 08:21 UTC, artemreyt commented on tests/listen_test.lua
> +#!/usr/bin/env tarantool
> Please format it for 80 columns and clean up debug comments.

Done.

2021-05-28 08:30 UTC, artemreyt commented
> Please format commit message for 80 columns.

Done.

2021-05-28 13:25 UTC, void234 commented on httpng.lua
> +function table.copy(t)
> It's impossible to add 'local' for field of global `table`.
> Also, I found that in Tarantool there is extended `table`. See [table module documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/table/).
> And there's already `copy()` method exists, which copies an array.
> But there's also such method that we need called `table.deepcopy()`.

Not sure we really need expensive deepcopy().
Not sure we need to modify `table` (that was just an example from stackoverflow).
Change it to local function with different name?

2021-05-28 13:29 UTC, void234 commented on httpng.lua
> +            error("impossible to parse URI: " .. listen_conf)
> Yes, this error is thrown if the last condition is false.
> Otherwise, goto is executed.

Are you absolutely sure about that?
`end` is not located where it should be, as far as I can see from your description.

2021-05-28 13:32 UTC, artemreyt commented on httpng.lua
> +function table.copy(t)
Why not to copy deep? It isn't hot path.

2021-05-28 13:57 UTC, void234 commented on tests/listen_test.lua
> +#!/usr/bin/env tarantool
> > Please format it for 80 columns and clean up debug comments.
> 
> Done.

If you really did that, you have not committed it. There is more than 80 columns.

What about moving this file to examples or using luatest?

2021-05-28 13:59 UTC, void234 requested changes
Good work, we are close but not there yet.

2021-05-30 20:45 UTC, artemreyt commented on httpng.lua
> +            error("impossible to parse URI: " .. listen_conf)
You're are right, `end` is placed in the wrong place.

2021-05-30 20:45 UTC, artemreyt commented on tests/listen_test.lua
> +#!/usr/bin/env tarantool
> If you really did that, you have not committed it. There is more than 80 columns.

Converted to spaces, 80 columns is ok. 
> What about moving this file to examples or using luatest?

Moved to examples.

2021-05-31 08:18 UTC, void234 commented on httpng.lua
> +        res = {}
It is an empty table already.

2021-05-31 08:29 UTC, void234 commented on httpng/httpng.c
> +			if ((ssl_ctx = get_tls_field_from_lua(L, listener_idx,
Why are you calling `get_tls_field_from_lua()` twice?

2021-05-31 08:37 UTC, void234 commented on httpng/httpng.c
> +sni_map_deinit(sni_map_t *sni_map)
This function is called on init error but not on shutdown, am I right? Are you sure you are freeing resources (`SSL_CTX_free()`/`free()`) on shutdown? Are you sure this wouldn't clash with `SSL_CTX_free()` in `close_listening_sockets()`?

It may be a good idea to use more informative names for such functions and/or add comments.

2021-05-31 08:42 UTC, void234 commented on httpng/httpng.c
> +	conf_sni_map_cleanup();
Hmm. Why are you freeing resources you have just allocated and configured?

2021-05-31 08:44 UTC, void234 requested changes
Bug hunt continues.

2021-06-01 16:05 UTC, artemreyt commented on httpng.lua
> +        res = {}
Removed.

2021-06-01 16:05 UTC, artemreyt commented on httpng/httpng.c
> +			if ((ssl_ctx = get_tls_field_from_lua(L, listener_idx,
Effects of refactoring. Removed the first one.

2021-06-01 16:06 UTC, artemreyt commented on httpng/httpng.c
> +sni_map_deinit(sni_map_t *sni_map)
> This function is called on init error but not on shutdown, am I right? Are you sure you are freeing resources (`SSL_CTX_free()`/`free()`) on shutdown?

You are right, I don't. Added `conf_sni_map_cleanup()` on shutdown.

> Are you sure this wouldn't clash with `SSL_CTX_free()` in `close_listening_sockets()`?

Yes, I am. They are freeing different ssl contexts.

> It may be a good idea to use more informative names for such functions and/or add comments.

Changed to the name `sni_map_free()` and added comments for this function.

2021-06-01 16:06 UTC, artemreyt commented on httpng/httpng.c
> +	conf_sni_map_cleanup();
Removed from here, I was a bug.

2021-06-03 12:20 UTC, void234 commented on examples/multilisten.lua
> +        -- https://foo.tarantool.io:8443 or https://bar.tarantool.io:8443 (in /etc/hosts uri should ref to 127.0.0.1)
80 columns. Again.

2021-06-03 12:25 UTC, void234 commented on httpng.lua
> +            if port == nil then
Merge these two lines?

2021-06-03 13:06 UTC, void234 approved these changes
Please rebase, fold commits, fix buildability on MacOS and merge.

2021-06-05 16:50 UTC, artemreyt commented on httpng.lua
> +            if port == nil then
Done.

2021-06-05 16:50 UTC, artemreyt commented on examples/multilisten.lua
> +        -- https://foo.tarantool.io:8443 or https://bar.tarantool.io:8443 (in /etc/hosts uri should ref to 127.0.0.1)
Done.

2021-06-05 17:01 UTC, merged

2021-06-06 08:28 UTC, Totktonada commented
Please, update the API description in the `doc/api.md` file.

2021-06-06 08:31 UTC, artemreyt commented
> Please, update the API description in the `doc/api.md` file.

See #158